### ISSUE TITLE
Lifetime still treated as singleton, eventhough i already set the lifetime to scoped

### ISSUE THREAD

**Issue by luthfi9999** [martinothamar/Mediator#78] opened 2023-01-15 10:24 UTC
Hello, thanks for the great library, In my current project, I use .Net 7 with EF 7.
okay, so,  I already set the options for the mediator like this :
![image](https://user-images.githubusercontent.com/37775981/212535256-10b248f5-7514-445f-857d-0e4d1cc27026.png)
But, when I run the code, i got this error from visual studio :
![image](https://user-images.githubusercontent.com/37775981/212535325-c8c53997-ac83-486c-8b98-46612b266d39.png)
So, as mentioned my command handler is still treated as a singleton, not a scoped somehow, do i miss any step?

N.B. If i change my service to singleton, everything worked, but got error later on, because my DbContext need to be defined as scoped.

Thank you very much for your answer

**Comment by martinothamar** [comment] 2023-01-15 13:18
Hmm not sure what could be wrong here. The ASP.NET Core clean architecture sample in the samples folder in this repo kind of follows the same pattern, using scoped registration. Here is the generated code for that project: 
![image](https://user-images.githubusercontent.com/5425986/212542894-2a1c88b2-b471-453b-b6d3-187b48e65c1a.png)
As you can see, everything is registered as scoped.

If you take a look at the samples project, maybe you can spot a difference from your own setup? 
It is located here: https://github.com/martinothamar/Mediator/tree/main/samples/ASPNET_Core_CleanArchitecture

**Comment by aveeraldsinha** [comment] 2023-01-17 12:35
@luthfi9999 : Even I was facing the same issue and you just need to call the below line in your application project.

public static IServiceCollection AddApplication(this IServiceCollection serviceCollection)
        {
               serviceCollection.AddMediator(options =>
                          {
                              options.Namespace = "*.Application";
                              options.ServiceLifetime = ServiceLifetime.Scoped;
                          });
              return serviceCollection;
       }

and call this AddApplication method in the program.cs class of the web api or presentation project

**Comment by martinothamar** [comment] 2023-03-01 18:36
Closing this for now since I'm not able to reproduce on my own. Will reopen if more info is reported

**Closed by martinothamar** 2023-03-01 18:36 UTC
